### ISSUE TITLE
Lazily look up credential on secrethub run

### ISSUE THREAD

**Issue by florisvdg** [secrethub/secrethub-cli#121]
Would be nice if the `run` command would not look for the credential if the `.env` file doesn't specify any secrets. If they're not there, then why bother looking for the credential?

To still be able to validate the credential (existence) upfront, a command `secrethub validate-credential` could be added.

**Comment by SimonBarendse** [comment]
Good suggestion! I'll create a PR for postponing the creation of the client in `secrethub run`.
We can add the `validate-credential` command later if there's more demand for it.
