### ISSUE TITLE
Unicode characters in passphrase breaks passphrase caching

### ISSUE THREAD

**Issue by jpcoenen** [secrethub/secrethub-cli#132]
If a user has `é` in his passphrase, caching of the passphrase with the OS's keyring breaks on MacOS. The following error message is returned: 

```
Encountered an error: cannot get passphrase from keyring: invalid character 'b' after top-level value (secrethub.cannot_get_keyring)`.
```

This might have something to do with the keyring returning a non-UTF-8-encoded string when this character is used, which breaks the json decoding of the stored value.

**Comment by mackenbach** [comment]
This is fixed in release `v0.26.0`, see #149
