### ISSUE TITLE
Add generate --clip flag

### ISSUE THREAD

**Issue by mackenbach** [secrethub/secrethub-cli#172]
We have the `--clip` flag in the read command and it makes a lot of sense to add it to the `generate` command too. 

```
  -c, --clip  Copy the secret value to the clipboard. The clipboard is
              automatically cleared after 45 seconds.
```

There's actually already a `TODO` comment in the code.

**Comment by SimonBarendse** [comment]
This is released in [v0.29.0](https://github.com/secrethub/secrethub-cli/releases/tag/v0.29.0)
