### ISSUE TITLE
Add flag to secrethub read to not print newline

### ISSUE THREAD

**Issue by florisvdg** [secrethub/secrethub-cli#262]
Like `echo -n foo` we could have: `secrethub read -n path/to/secret`.

**Comment by mackenbach** [comment]
Thanks for the suggestion @antonbabenko

**Comment by SimonBarendse** [comment]
The flag is added in https://github.com/secrethub/secrethub-cli/pull/263 and will be included in the next release.

**Comment by jpcoenen** [comment]
This is released in `v0.38.0`.
