### ISSUE TITLE
Snap: Errors with clipboard and file options for secrethub write (CLI)

### ISSUE THREAD

**Issue by DVAlexHiggs** [secrethub/secrethub-cli#338]
I've been sing secrethub for a while now and keep intermittently coming across these issues and have never found the source nor managed to fix them, resorting to copy and pasting manually as a workaround.

When I use the `secrethub write -c` I get the following error:

```
Encountered an error: cannot read from clipboard: No clipboard utilities available. Please install xsel, xclip, wl-clipboard or Termux:API add-on for termux-clipboard-get/set. (clipboard.cannot_read) 
```

I actually have both `xsel` and `xclip` installed. I've tried uninstalling one to see if it was a conflict of sorts, but received the same error.

When I use the `secrethub write -i` I get the following error:

```
Encountered an error: could not read the input file <file name here>: open <file name here>: permission denied (secrethub.in_file_read_error) 
```

I've tried setting 777 permissions on the file in question and I still get this issue.

This is happening on Ubuntu 20.04.1 LTS, using the `secrethub-cli`snap.

`secrethub --version` gives: `secrethub version 0.34.0, build 549b444`

I've done a lot of googling and have been unable to find anything online or in the SecretHub docmentation. I hope we can get to the bottom of this, as it's a real pain having to copy and paste manually at the moment.

EDIT:

I've discovered that this ONLY occurs on the snap version. The same commands using the `secrethub-cli` downloaded from APT worked first time.

**Comment by florisvdg** [comment]
Unfortunately, we [dropped support for Snap in February](https://github.com/secrethub/secrethub-cli/releases/tag/v0.35.0) and [delisted](https://snapcraft.io/search?q=secrethub) SecretHub from the Snap store, exactly because of these types of issues (related to the very restrictive sandbox model that Snap imposes).

So we recommend that you switch to one of the numerous [other CLI installation methods / package managers](https://secrethub.io/docs/reference/cli/install/) available.

**Comment by DVAlexHiggs** [comment]
Ah! That makes sense. Thanks. I googled to find a snap for secrethub and google still displays results:

https://snapcraft.io/install/secrethub-cli/ubuntu

So for someone who doesn't know about the discontinuation it can be misleading.

**Comment by florisvdg** [comment]
Good point, we'll look into that!
