### ISSUE TITLE
Add a --parents flag to the mkdir command

### ISSUE THREAD

**Issue by SimonBarendse** [secrethub/secrethub-cli#36]
When creating a full tree for a new project, it is often needed to create nested directories. To be able to do so without having to do a lot of monkey work, let's add a `--parents` flag to the `mkdir` command that creates the parent directories as well when these do not exist yet.

This flag would work exactly as the `--parents` flag on the [unix `mkdir`](http://manpages.ubuntu.com/manpages/bionic/man1/mkdir.1.html) command works; It will create the parent directories as well when these do not exist yet and it will not error when all directories already exist.

```
-p, --parents (bool)

   make parent directories as needed
```

**Comment by jpcoenen** [comment]
https://github.com/secrethub/secrethub-cli/pull/217 is merged and scheduled for `v0.33.0`.
