### ISSUE TITLE
Unable to install CLI on Mac OS Big Sur

### ISSUE THREAD

**Issue by xpnewmedia** [secrethub/secrethub-cli#374]
[https://signup.secrethub.io/install](https://signup.secrethub.io/install)

When following these instructions from the above page:
```
brew install secrethub/tools/secrethub-cli
secrethub init --setup-code xx-xxx-xxxx-xxx-xx
```

I get the following error:

```
Encountered an error: unknown long flag '--setup-code'
```

My system is:
Mac OS Big Sur
11.2.1 (20D75)

My cli version is:
secrethub version 0.39.0, build cd99b29

I was unable to install and proceed using the service.

**Comment by SimonBarendse** [comment]
Hi @xpnewmedia thank you for opening this issue.

The `--setup-code` flag has been added in [`v0.41.0`](https://github.com/secrethub/secrethub-cli/releases/tag/v0.41.0), so the problem appears to be an outdated CLI installation.

The latest version in the [SecretHub HomeBrew Tap](https://github.com/secrethub/homebrew-tools) is currently `v0.41.2`.

Could you try running `brew upgrade secrethub/tools/secrethub-cli` and then retry the `secrethub init --setup-code xx-xxx-xxxx-xxx-xx` command?

**Comment by SimonBarendse** [comment]
Did this resolve your issue?

I'm closing this for now, but feel free to re-open in case this doesn't solve the issue for you.
